### ISSUE TITLE
Capitalize 'login' function to make it a React componenet

### ISSUE THREAD

**Issue by Snarr** [cis3296f22/03-EBMS#18]
| Name | Status | Preview | Updated |
| :--- | :----- | :------ | :------ |
| **03-ebms** | ❌ Failed ([Inspect](https://vercel.com/ebms/03-ebms/GKoGGccF5Ayw8jmTEerCDjoZEDjq)) |  | Nov 11, 2022 at 0:44AM (UTC) |

_Originally posted by @vercel[bot] in https://github.com/cis3296f22/03-EBMS/issues/17#issuecomment-1311087873_

**Comment by timlopesTU** [comment]
Fixed the 'Login' function
